Functions for creating raster layer and map
EcoForecast/NEFI_tick pull request #2
Opened 2017-10-06 20:13 UTC by JohnRFoster

Changed code to have functions instead of hard coding the raster and maps

2017-10-09 10:17 UTC, mdietze requested changes
There's two binary files that have been added, GADM_2.8_USA_adm0.rds and GADM_2.8_USA_adm1.rds, but they aren't referenced anywhere in the file so it's not clear how/why they're used. Also, in general it's not good practice to include inputs/outputs in a git repo -- they bloat the repository and version control can't manage their differences over time easily. If these files are NOT required, you'll need to do some non-trivial advanced git work to remove them in a way that doesn't retain them in the repo history (which is needed to prevent bloat) -- touch base with folks in the lab (especially Alexey) for help.

Also not clear why there's a NEFI_tick subfolder added within what everyone else will view as a NEFI_tick folder.

2017-10-09 10:17 UTC, mdietze commented on .gitignore
> +=======
This shows a merge conflict, which needs to be resolved before the code can be pulled

2017-10-09 10:17 UTC, mdietze commented on Citizen Science API.R
> +library(rgbif)
It appears that you changed the file name to switch _ to spaces. Please change back. First, it's bad practice to include spaces in file names. Second, the change in name makes it impossible to see the difference between the previous version and the new version -- git things these are completely different files.

2017-10-19 12:47 UTC, JohnRFoster commented
Cleaned up repo, and changed script name

2017-10-19 20:10 UTC, mdietze reviewed
script name still not back to what it was originally. Still merge conflicts in gitignore

2018-07-24 12:10 UTC, mdietze requested changes

2018-07-24 12:10 UTC, mdietze commented on CaryMouse_MetOut_code.R
> +prin("END FILE")
Is this supposed to be `print`

2018-07-24 12:10 UTC, mdietze commented on CaryTickMet.R
> +        file = paste("/projectnb/dietzelab/fosterj/Previous_Runs_Tick/CaryTickNull_NegBinomLarv_", xx, ".rds",
general suggestion: Define folder names near the top of any file/function and then construct file paths by using the `file.path` function to combine that folder with the specific file name. This makes the code much more portable

2018-07-24 12:10 UTC, mdietze commented on CaryTick_MonthlyMet.R
> +noise <- function(dat, sd){
There's too much in the PR for me to follow everything, but I feel like there is a **LOT** of redundant code in this repo. If you're reusing functions, define them once in their own files. If you're writing the same code again and again (or worse, copy-and-pasting) then you should figure out what parts are repeated and put them in functions. For example, I think a lot of your files contain code that is identical except for small differences in JAGS models -- to me that seems like something better handled by having one bit of code that handles the I/O for a specific class of models and then pass different individual models to that code.

2018-07-24 12:10 UTC, mdietze commented on CaryTick_miceTwo.R
> +library(rjags)
These files have no headers explaining what the different models are.  This example, where there's a `CaryTick_miceOne.R` and a `CaryTick_miceTwo.R` is particularly bad as there's no one other than you who would have any idea what these different models are. And I guarantee that in a few months you won't know what they are either.

2018-07-24 12:10 UTC, mdietze commented on Cary_pop/CaryTick
> +"","Year","Grid","Date","Larvae.m2","Nymphs.m2","Adults.m2","X","day.of.year"
Do you have permission to make the Cary data public? If not, then these data files should not be in the PR

2018-07-24 12:10 UTC, mdietze commented on Cary_pop/Met Data/DAILY1995.csv
> +DATE,AVE_TEMP,AVE_RH,TOT_PREC,MIN_TEMP,MIN_TEMT,MIN_RH,MIN_RHT,MAX_WS,MAX_WST,MAX_TEMP,MAX_TEMT,MAX_RH,MAX_RHT,MAX_GSW,MAX_GSWT,MAX_DSW,MAX_DSWT,MAX_NETR,MAX_NETT,MAX_GPAR,MAX_GPAT,MAX_DPAR,MAX_DPAT,
Please don't use spaces in folder names

2020-03-03 19:38 UTC, closed without merging